import type { PrismaClient } from '../../src/generated/prisma/client.js';
import type { ActivityStatus, ActivityType } from '../../src/generated/prisma/enums.js';
import { dateOffset, logStep, requireEntry, seedId, timeOfDay } from './helpers.js';
import type { OrganizationCatalog } from './organizations.seed.js';
import type { SeedProgram } from './programs.seed.js';
import type { SeedSpeaker } from './speakers.seed.js';

type ProgramRef = { type: 'unit'; unitKey: string } | { type: 'additional'; programKey: string };

interface ActivityCatalogEntry {
  key: string;
  program: ProgramRef;
  name: string;
  description: string;
  type: ActivityType;
  dayOffset: number;
  startHour: number;
  endHour: number;
  maxCapacity: number | null;
  classroomKey: string | null;
  speakerKeys: readonly string[];
  status: ActivityStatus;
  equipment: readonly string[];
  bannerUrl?: string | null;
  cancelReason?: string | null;
}

export const ACTIVITIES: readonly ActivityCatalogEntry[] = [
  {
    key: 'fic-charla-puentes',
    program: { type: 'unit', unitKey: 'fic' },
    name: 'Charla: Innovación en Puentes',
    description: 'Charla técnica sobre nuevas metodologías de diseño de puentes.',
    type: 'TALK',
    dayOffset: -30,
    startHour: 10,
    endHour: 12,
    maxCapacity: 60,
    classroomKey: 'aula-101',
    speakerKeys: ['speaker-carlos'],
    status: 'COMPLETED',
    equipment: ['Proyector', 'Pizarra'],
  },
  {
    key: 'fic-taller-drones',
    program: { type: 'unit', unitKey: 'fic' },
    name: 'Taller de Topografía con Drones',
    description: 'Taller práctico de levantamiento topográfico con drones.',
    type: 'WORKSHOP',
    dayOffset: 14,
    startHour: 9,
    endHour: 12,
    maxCapacity: 24,
    classroomKey: 'lab-electronica',
    speakerKeys: ['org-fic', 'speaker-externo-luisa'],
    status: 'SCHEDULED',
    equipment: ['Dron', 'Proyector', 'Estación total'],
  },
  {
    key: 'fic-charla-cancelada',
    program: { type: 'unit', unitKey: 'fic' },
    name: 'Charla: Gestión de Proyectos Viales',
    description: 'Charla cancelada por reprogramación del ponente.',
    type: 'TALK',
    dayOffset: 7,
    startHour: 8,
    endHour: 10,
    maxCapacity: 40,
    classroomKey: 'aula-101',
    speakerKeys: ['speaker-carlos'],
    status: 'CANCELLED',
    equipment: ['Proyector'],
    cancelReason: 'Charla cancelada por reprogramación del ponente.',
  },
  {
    key: 'fie-seminario-smartgrids',
    program: { type: 'unit', unitKey: 'fie' },
    name: 'Seminario de Smart Grids',
    description: 'Seminario sobre redes eléctricas inteligentes y almacenamiento.',
    type: 'SEMINAR',
    dayOffset: 18,
    startHour: 9,
    endHour: 11,
    maxCapacity: 120,
    classroomKey: 'auditorio',
    speakerKeys: ['speaker-carlos', 'speaker-externo-marco'],
    status: 'SCHEDULED',
    equipment: ['Proyector', 'Micrófono'],
  },
  {
    key: 'fii-taller-logistica',
    program: { type: 'unit', unitKey: 'fii' },
    name: 'Taller de Logística 4.0',
    description: 'Taller de optimización de cadenas de suministro con analítica.',
    type: 'WORKSHOP',
    dayOffset: -25,
    startHour: 14,
    endHour: 17,
    maxCapacity: 35,
    classroomKey: 'aula-201',
    speakerKeys: ['speaker-diana'],
    status: 'COMPLETED',
    equipment: ['Proyector', 'Computadoras'],
  },
  {
    key: 'fii-charla-seguridad',
    program: { type: 'unit', unitKey: 'fii' },
    name: 'Charla de Seguridad Industrial',
    description: 'Buenas prácticas de seguridad e higiene ocupacional.',
    type: 'TALK',
    dayOffset: 21,
    startHour: 10,
    endHour: 12,
    maxCapacity: 40,
    classroomKey: 'aula-102',
    speakerKeys: ['org-fii'],
    status: 'SCHEDULED',
    equipment: ['Proyector'],
  },
  {
    key: 'fim-charla-mantenimiento',
    program: { type: 'unit', unitKey: 'fim' },
    name: 'Charla de Mantenimiento Predictivo',
    description: 'Introducción al mantenimiento predictivo con sensores IoT.',
    type: 'TALK',
    dayOffset: 25,
    startHour: 9,
    endHour: 11,
    maxCapacity: 35,
    classroomKey: 'aula-201',
    speakerKeys: ['org-fim'],
    status: 'SCHEDULED',
    equipment: ['Proyector', 'Sensores'],
  },
  {
    key: 'fisc-workshop-ciberseguridad',
    program: { type: 'unit', unitKey: 'fisc' },
    name: 'Workshop de Ciberseguridad Defensiva',
    description: 'Ejercicios de respuesta a incidentes y análisis de vulnerabilidades.',
    type: 'WORKSHOP',
    dayOffset: -21,
    startHour: 14,
    endHour: 17,
    maxCapacity: 25,
    classroomKey: 'lab-redes',
    speakerKeys: ['speaker-ana'],
    status: 'COMPLETED',
    equipment: ['Computadoras', 'Proyector'],
  },
  {
    key: 'fisc-charla-ia',
    program: { type: 'unit', unitKey: 'fisc' },
    name: 'Charla de Inteligencia Artificial Aplicada',
    description: 'Casos de uso de IA en la industria panameña.',
    type: 'TALK',
    dayOffset: 0,
    startHour: 8,
    endHour: 17,
    maxCapacity: 80,
    classroomKey: null,
    speakerKeys: ['speaker-ana'],
    status: 'ONGOING',
    equipment: ['Proyector', 'Micrófono'],
  },
  {
    key: 'fcyt-seminario-alimentos',
    program: { type: 'unit', unitKey: 'fcyt' },
    name: 'Seminario de Alimentos Funcionales',
    description: 'Avances en alimentos funcionales y nutracéuticos.',
    type: 'SEMINAR',
    dayOffset: 28,
    startHour: 9,
    endHour: 11,
    maxCapacity: 24,
    classroomKey: 'lab-quimica',
    speakerKeys: ['speaker-ivan'],
    status: 'SCHEDULED',
    equipment: ['Proyector', 'Mesas'],
  },
  {
    key: 'sub-acad-taller-curriculo',
    program: { type: 'unit', unitKey: 'sub-acad' },
    name: 'Taller de Diseño Curricular por Competencias',
    description: 'Taller para coordinadores académicos sobre diseño curricular.',
    type: 'WORKSHOP',
    dayOffset: 30,
    startHour: 8,
    endHour: 12,
    maxCapacity: 60,
    classroomKey: 'sala-conferencias',
    speakerKeys: ['org-sub-acad'],
    status: 'SCHEDULED',
    equipment: ['Proyector', 'Pizarra'],
  },
  {
    key: 'sub-admin-induccion',
    program: { type: 'unit', unitKey: 'sub-admin' },
    name: 'Inducción de Procesos Administrativos',
    description: 'Inducción al personal administrativo de nuevo ingreso.',
    type: 'TALK',
    dayOffset: -18,
    startHour: 8,
    endHour: 10,
    maxCapacity: 40,
    classroomKey: 'aula-102',
    speakerKeys: ['org-sub-admin'],
    status: 'COMPLETED',
    equipment: ['Proyector'],
  },
  {
    key: 'sub-vida-salud-mental',
    program: { type: 'unit', unitKey: 'sub-vida' },
    name: 'Jornada de Salud Mental',
    description: 'Charla sobre manejo del estrés y bienestar emocional.',
    type: 'TALK',
    dayOffset: 32,
    startHour: 14,
    endHour: 16,
    maxCapacity: 120,
    classroomKey: 'auditorio',
    speakerKeys: ['org-sub-vida'],
    status: 'SCHEDULED',
    equipment: ['Proyector', 'Micrófono'],
  },
  {
    key: 'sub-ipe-propiedad-intelectual',
    program: { type: 'unit', unitKey: 'sub-ipe' },
    name: 'Seminario de Propiedad Intelectual',
    description: 'Protección de resultados de investigación y transferencia.',
    type: 'SEMINAR',
    dayOffset: 35,
    startHour: 13,
    endHour: 15,
    maxCapacity: 60,
    classroomKey: 'sala-conferencias',
    speakerKeys: ['org-sub-ipe'],
    status: 'SCHEDULED',
    equipment: ['Proyector'],
  },
  {
    key: 'semana-ic-taller-estructuras',
    program: { type: 'additional', programKey: 'semana-ic' },
    name: 'Taller de Análisis Estructural',
    description: 'Taller de modelado estructural asistido por computadora.',
    type: 'WORKSHOP',
    dayOffset: -33,
    startHour: 9,
    endHour: 12,
    maxCapacity: 20,
    classroomKey: 'lab-mecanica',
    speakerKeys: ['org-fic'],
    status: 'COMPLETED',
    equipment: ['Computadoras', 'Mesa de ensayos'],
  },
  {
    key: 'semana-ic-charla-puentes',
    program: { type: 'additional', programKey: 'semana-ic' },
    name: 'Conferencia de Puentes y Estructuras',
    description: 'Conferencia magistral sobre puentes de gran luz.',
    type: 'CONFERENCE',
    dayOffset: -31,
    startHour: 10,
    endHour: 12,
    maxCapacity: 40,
    classroomKey: 'aula-101',
    speakerKeys: ['speaker-carlos'],
    status: 'COMPLETED',
    equipment: ['Proyector'],
  },
  {
    key: 'semana-ic-taller-topografia',
    program: { type: 'additional', programKey: 'semana-ic' },
    name: 'Taller de Topografía Satelital',
    description: 'Uso de GNSS en levantamientos topográficos.',
    type: 'WORKSHOP',
    dayOffset: -29,
    startHour: 14,
    endHour: 17,
    maxCapacity: 24,
    classroomKey: 'lab-electronica',
    speakerKeys: ['org-fic'],
    status: 'COMPLETED',
    equipment: ['GNSS', 'Proyector'],
  },
  {
    key: 'cit-conferencia-ia',
    program: { type: 'additional', programKey: 'congreso-cit' },
    name: 'Conferencia Magistral de IA',
    description: 'Conferencia inaugural del congreso sobre inteligencia artificial.',
    type: 'CONFERENCE',
    dayOffset: 16,
    startHour: 9,
    endHour: 11,
    maxCapacity: 120,
    classroomKey: 'auditorio',
    speakerKeys: ['speaker-ana'],
    status: 'SCHEDULED',
    equipment: ['Proyector', 'Micrófono', 'Streaming'],
  },
  {
    key: 'cit-taller-ciberseguridad',
    program: { type: 'additional', programKey: 'congreso-cit' },
    name: 'Taller de Ciberseguridad Ofensiva',
    description: 'Laboratorio controlado de pruebas de penetración.',
    type: 'WORKSHOP',
    dayOffset: 18,
    startHour: 14,
    endHour: 17,
    maxCapacity: 25,
    classroomKey: 'lab-redes',
    speakerKeys: ['speaker-ana'],
    status: 'SCHEDULED',
    equipment: ['Computadoras', 'Proyector'],
  },
  {
    key: 'cit-panel-blockchain',
    program: { type: 'additional', programKey: 'congreso-cit' },
    name: 'Panel de Blockchain y Fintech',
    description: 'Panel de discusión con expertos en tecnología financiera.',
    type: 'PANEL',
    dayOffset: 20,
    startHour: 10,
    endHour: 12,
    maxCapacity: 60,
    classroomKey: 'sala-conferencias',
    speakerKeys: ['speaker-diana'],
    status: 'SCHEDULED',
    equipment: ['Proyector', 'Micrófono'],
  },
  {
    key: 'bienestar-charla-salud-mental',
    program: { type: 'additional', programKey: 'jornada-bienestar' },
    name: 'Charla de Manejo del Estrés',
    description: 'Herramientas psicológicas para el manejo del estrés académico.',
    type: 'TALK',
    dayOffset: 23,
    startHour: 10,
    endHour: 12,
    maxCapacity: 120,
    classroomKey: 'auditorio',
    speakerKeys: ['org-sub-vida'],
    status: 'SCHEDULED',
    equipment: ['Proyector', 'Micrófono'],
  },
  {
    key: 'bienestar-taller-nutricion',
    program: { type: 'additional', programKey: 'jornada-bienestar' },
    name: 'Taller de Nutrición Saludable',
    description: 'Hábitos alimenticios para la vida universitaria.',
    type: 'WORKSHOP',
    dayOffset: 25,
    startHour: 14,
    endHour: 16,
    maxCapacity: 35,
    classroomKey: 'aula-201',
    speakerKeys: ['org-sub-vida'],
    status: 'SCHEDULED',
    equipment: ['Proyector', 'Muestras'],
  },
  {
    key: 'foro-ipe-conferencia-investigacion',
    program: { type: 'additional', programKey: 'foro-ipe' },
    name: 'Conferencia de Investigación Aplicada',
    description: 'Resultados de proyectos de investigación aplicada.',
    type: 'CONFERENCE',
    dayOffset: -320,
    startHour: 9,
    endHour: 11,
    maxCapacity: 60,
    classroomKey: 'sala-conferencias',
    speakerKeys: ['org-sub-ipe'],
    status: 'COMPLETED',
    equipment: ['Proyector'],
  },
  {
    key: 'foro-ipe-taller-publicaciones',
    program: { type: 'additional', programKey: 'foro-ipe' },
    name: 'Taller de Publicaciones Científicas',
    description: 'Cómo publicar en revistas indexadas.',
    type: 'WORKSHOP',
    dayOffset: -318,
    startHour: 14,
    endHour: 16,
    maxCapacity: 40,
    classroomKey: 'aula-102',
    speakerKeys: ['org-sub-ipe'],
    status: 'COMPLETED',
    equipment: ['Proyector', 'Pizarra'],
  },
  {
    key: 'cit-conferencia-robotica',
    program: { type: 'additional', programKey: 'congreso-cit' },
    name: 'Conferencia de Robótica e Industria 4.0',
    description: 'Conferencia sobre robótica colaborativa y automatización industrial.',
    type: 'CONFERENCE',
    dayOffset: 17,
    startHour: 14,
    endHour: 16,
    maxCapacity: 100,
    classroomKey: 'auditorio',
    speakerKeys: ['speaker-diana'],
    status: 'SCHEDULED',
    equipment: ['Proyector', 'Micrófono'],
  },
  {
    key: 'fcyt-conferencia-biotecnologia',
    program: { type: 'unit', unitKey: 'fcyt' },
    name: 'Conferencia de Biotecnología Aplicada',
    description: 'Conferencia sobre aplicaciones biotecnológicas en la industria local.',
    type: 'CONFERENCE',
    dayOffset: 40,
    startHour: 13,
    endHour: 15,
    maxCapacity: 150,
    classroomKey: 'aula-magna',
    speakerKeys: ['speaker-ivan'],
    status: 'SCHEDULED',
    equipment: ['Proyector', 'Micrófono', 'Streaming'],
  },
  {
    key: 'fie-conferencia-vlsi',
    program: { type: 'unit', unitKey: 'fie' },
    name: 'Conferencia de Microelectrónica VLSI',
    description: 'Conferencia sobre diseño de circuitos integrados y microelectrónica.',
    type: 'CONFERENCE',
    dayOffset: 33,
    startHour: 10,
    endHour: 12,
    maxCapacity: 80,
    classroomKey: 'auditorio',
    speakerKeys: ['speaker-carlos'],
    status: 'SCHEDULED',
    equipment: ['Proyector'],
    bannerUrl: '/banners/conferencia-vlsi-2026.jpg',
  },
  {
    key: 'cit-panel-mujeres-stem',
    program: { type: 'additional', programKey: 'congreso-cit' },
    name: 'Panel de Mujeres en STEM',
    description: 'Panel sobre trayectorias y retos de las mujeres en ciencia y tecnología.',
    type: 'PANEL',
    dayOffset: 19,
    startHour: 15,
    endHour: 17,
    maxCapacity: 60,
    classroomKey: 'sala-conferencias',
    speakerKeys: ['speaker-ana', 'speaker-lucia'],
    status: 'SCHEDULED',
    equipment: ['Proyector', 'Micrófono'],
  },
  {
    key: 'fim-panel-mantenimiento-industrial',
    program: { type: 'unit', unitKey: 'fim' },
    name: 'Panel de Mantenimiento Industrial',
    description: 'Panel de expertos sobre tendencias en mantenimiento industrial.',
    type: 'PANEL',
    dayOffset: 45,
    startHour: 10,
    endHour: 12,
    maxCapacity: 60,
    classroomKey: 'sala-conferencias',
    speakerKeys: ['org-fim', 'speaker-roberto'],
    status: 'SCHEDULED',
    equipment: ['Proyector', 'Micrófono'],
  },
  {
    key: 'sub-ipe-panel-innovacion',
    program: { type: 'unit', unitKey: 'sub-ipe' },
    name: 'Panel de Transferencia Tecnológica',
    description: 'Panel sobre transferencia de tecnología y vinculación universidad-empresa.',
    type: 'PANEL',
    dayOffset: 38,
    startHour: 10,
    endHour: 12,
    maxCapacity: 60,
    classroomKey: 'sala-conferencias',
    speakerKeys: ['org-sub-ipe', 'speaker-roberto'],
    status: 'SCHEDULED',
    equipment: ['Proyector', 'Micrófono'],
  },
  {
    key: 'congreso-cit-curso-machine-learning',
    program: { type: 'additional', programKey: 'congreso-cit' },
    name: 'Curso Intensivo de Machine Learning',
    description: 'Curso práctico de modelos de aprendizaje automático con Python.',
    type: 'COURSE',
    dayOffset: 18,
    startHour: 8,
    endHour: 12,
    maxCapacity: 30,
    classroomKey: 'lab-computo-1',
    speakerKeys: ['speaker-ana'],
    status: 'SCHEDULED',
    equipment: ['Computadoras', 'Proyector'],
  },
  {
    key: 'bienestar-curso-primeros-auxilios',
    program: { type: 'additional', programKey: 'jornada-bienestar' },
    name: 'Curso de Primeros Auxilios',
    description: 'Curso básico de primeros auxilios y respuesta ante emergencias.',
    type: 'COURSE',
    dayOffset: 26,
    startHour: 8,
    endHour: 12,
    maxCapacity: 45,
    classroomKey: 'aula-202',
    speakerKeys: ['org-sub-vida'],
    status: 'SCHEDULED',
    equipment: ['Proyector', 'Botiquín'],
  },
  {
    key: 'feria-cientifica-curso-metodologia',
    program: { type: 'additional', programKey: 'feria-cientifica' },
    name: 'Curso de Metodología Científica',
    description: 'Curso de diseño de investigación y comunicación de resultados.',
    type: 'COURSE',
    dayOffset: 41,
    startHour: 9,
    endHour: 13,
    maxCapacity: 150,
    classroomKey: 'aula-magna',
    speakerKeys: ['org-fcyt'],
    status: 'SCHEDULED',
    equipment: ['Proyector', 'Pizarra'],
  },
  {
    key: 'fii-curso-seguridad-laboral',
    program: { type: 'unit', unitKey: 'fii' },
    name: 'Curso de Seguridad y Salud Ocupacional',
    description: 'Curso de prevención de riesgos laborales y normativa vigente.',
    type: 'COURSE',
    dayOffset: 52,
    startHour: 13,
    endHour: 17,
    maxCapacity: 45,
    classroomKey: 'aula-202',
    speakerKeys: ['org-fii', 'speaker-diana', 'speaker-externo-jorge'],
    status: 'SCHEDULED',
    equipment: ['Proyector', 'Pizarra'],
  },
  {
    key: 'congreso-cit-competicion-hackathon',
    program: { type: 'additional', programKey: 'congreso-cit' },
    name: 'Hackathon de Innovación Abierta',
    description: 'Competencia por equipos para resolver retos tecnológicos en 12 horas.',
    type: 'COMPETITION',
    dayOffset: 20,
    startHour: 8,
    endHour: 20,
    maxCapacity: 150,
    classroomKey: 'plaza-central',
    speakerKeys: ['speaker-ana', 'speaker-carlos'],
    status: 'SCHEDULED',
    equipment: ['Computadoras', 'Red', 'Proyector'],
  },
  {
    key: 'fic-competicion-puentes',
    program: { type: 'unit', unitKey: 'fic' },
    name: 'Competencia de Maquetas de Puentes',
    description: 'Competencia estudiantil de diseño y resistencia de maquetas de puentes.',
    type: 'COMPETITION',
    dayOffset: -29,
    startHour: 9,
    endHour: 12,
    maxCapacity: 20,
    classroomKey: 'lab-mecanica',
    speakerKeys: ['org-fic'],
    status: 'COMPLETED',
    equipment: ['Mesa de ensayos', 'Herramientas'],
  },
  {
    key: 'fie-competicion-robotica-draft',
    program: { type: 'unit', unitKey: 'fie' },
    name: 'Competencia de Robótica',
    description: 'Competencia de robots autónomos (borrador sin publicar).',
    type: 'COMPETITION',
    dayOffset: 46,
    startHour: 9,
    endHour: 15,
    maxCapacity: 25,
    classroomKey: 'lab-electronica',
    speakerKeys: ['org-fie'],
    status: 'DRAFT',
    equipment: ['Robots', 'Herramientas'],
  },
  {
    key: 'fic-taller-acuatica-draft',
    program: { type: 'unit', unitKey: 'fic' },
    name: 'Taller de Ingeniería Acuática',
    description: 'Borrador de taller sobre modelación hidráulica (sin publicar).',
    type: 'WORKSHOP',
    dayOffset: 50,
    startHour: 9,
    endHour: 12,
    maxCapacity: null,
    classroomKey: null,
    speakerKeys: [],
    status: 'DRAFT',
    equipment: [],
  },
  {
    key: 'fcyt-seminario-cancelado',
    program: { type: 'unit', unitKey: 'fcyt' },
    name: 'Seminario de Química Verde',
    description: 'Seminario cancelado por disponibilidad del laboratorio.',
    type: 'SEMINAR',
    dayOffset: 27,
    startHour: 9,
    endHour: 11,
    maxCapacity: 30,
    classroomKey: 'lab-quimica',
    speakerKeys: ['org-fcyt'],
    status: 'CANCELLED',
    equipment: ['Proyector'],
    cancelReason: 'Cancelado por disponibilidad del laboratorio de química.',
  },
  {
    key: 'sub-vida-jornada-servicios',
    program: { type: 'unit', unitKey: 'sub-vida' },
    name: 'Jornada de Servicios Estudiantiles',
    description: 'Feria de servicios y orientación para la comunidad estudiantil.',
    type: 'OTHER',
    dayOffset: 29,
    startHour: 9,
    endHour: 14,
    maxCapacity: 120,
    classroomKey: 'plaza-central',
    speakerKeys: ['org-sub-vida'],
    status: 'SCHEDULED',
    equipment: ['Pérgola', 'Mesas'],
  },
];

export interface SeedActivity {
  id: string;
  key: string;
  programId: string;
  date: Date;
  startHour: number;
  endHour: number;
}

export interface SeedActivityInput {
  catalog: OrganizationCatalog;
  additionalPrograms: Map<string, SeedProgram>;
  speakers: Map<string, SeedSpeaker>;
  classrooms: Map<string, string>;
}

const resolveProgramId = (
  program: ProgramRef,
  input: Pick<SeedActivityInput, 'catalog' | 'additionalPrograms'>,
): string => {
  if (program.type === 'unit') {
    return requireEntry(input.catalog.units, program.unitKey, 'unidad organizativa').programId;
  }
  return requireEntry(input.additionalPrograms, program.programKey, 'programa adicional').id;
};

export const seedActivities = async (
  prisma: PrismaClient,
  input: SeedActivityInput,
  now: Date = new Date(),
): Promise<Map<string, SeedActivity>> => {
  logStep('Sembrando actividades y equipamiento...');
  const activities = new Map<string, SeedActivity>();

  for (const activity of ACTIVITIES) {
    const programId = resolveProgramId(activity.program, input);
    const date = dateOffset(activity.dayOffset, now);
    const startTime = timeOfDay(activity.startHour);
    const endTime = timeOfDay(activity.endHour);
    const classroomId = activity.classroomKey
      ? requireEntry(input.classrooms, activity.classroomKey, 'aula')
      : null;
    const speakerIds = activity.speakerKeys.map(
      (speakerKey) => requireEntry(input.speakers, speakerKey, 'ponente').id,
    );
    const activityId = seedId('activity', activity.key);

    const data = {
      name: activity.name,
      description: activity.description,
      type: activity.type,
      date,
      startTime,
      endTime,
      maxCapacity: activity.maxCapacity,
      bannerUrl: activity.bannerUrl ?? null,
      status: activity.status,
      cancelReason: activity.cancelReason ?? null,
      eventProgramId: programId,
      classroomId,
    };

    const existing = await prisma.activity.findUnique({
      where: { id: activityId },
      select: { id: true },
    });

    const record = existing
      ? await prisma.activity.update({
          where: { id: existing.id },
          data,
          select: { id: true },
        })
      : await prisma.activity.create({
          data: { id: activityId, ...data },
          select: { id: true },
        });

    await prisma.activityEquipment.deleteMany({ where: { activityId: record.id } });
    await prisma.activityEquipment.createMany({
      data: activity.equipment.map((name) => ({ activityId: record.id, name })),
      skipDuplicates: true,
    });

    await prisma.activitySpeaker.deleteMany({ where: { activityId: record.id } });
    await prisma.activitySpeaker.createMany({
      data: speakerIds.map((speakerId) => ({ activityId: record.id, speakerId })),
      skipDuplicates: true,
    });

    activities.set(activity.key, {
      id: record.id,
      key: activity.key,
      programId,
      date,
      startHour: activity.startHour,
      endHour: activity.endHour,
    });
  }

  return activities;
};
